# 应用名称
spring:
  application:
    name: kb-oauth
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 8.140.48.121
    password: m****5
    port: 6379
    timeout: 5000 #连接超时 毫秒
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.140.48.121:3306/kb_oauth?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    username: root
    password: M********5
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 8.140.48.121:8848
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 9002
auth:
  ttl: 1200 #token存储到Redis的过期时间
  clientId: k****i #客户端id
  clientSecret: k****i #客户端秘钥
  cookieDomain: 192.168.43.75 #Cookie保存对应的域名
  cookieMaxAge: -1 #cookie过期时间，-1表示浏览器关闭则销毁
#从GitHub获取的信息
github:
  oauth:
    clientId: 1530106af0a44b467aec
    clientSecret: 1b**********************98e
    callback: http://localhost:9002/oauth/callback
ribbon:
  ReadTimeout: 5000
  ConnectionTimeout: 5000