# 应用名称
spring:
  application:
    name: kb-oauth
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 8.140.48.121
    password: mwz656565
    port: 6379
    timeout: 5000 #连接超时 毫秒
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.140.48.121:3306/kb_oauth?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 8.140.48.121:8848
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 9002
auth:
  ttl: 1200 #token存储到Redis的过期时间
  clientId: kaibai #客户端id
  clientSecret: kaibai #客户端秘钥
  cookieDomain: 192.168.43.75 #Cookie保存对应的域名
  cookieMaxAge: -1 #cookie过期时间，-1表示浏览器关闭则销毁
ribbon:
  ReadTimeout: 5000
  ConnectionTimeout: 5000